<?php

use Illuminate\Database\Seeder;
use App\Profile;


class ProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create();
        
        for ($i = 0; $i< 50; $i++)
        {
            Profile::Create([
            'id'         => $i+1,
            'nickname'   => $faker->word,
            //Location must be between 3001/3490 as these are valid for csv 'Melbourne'.
            'location'   => $faker->randomElement(static::$location_table),
            'status'     => $faker->randomElement($array = array ('single', 'married', 'divorced', 'complicated')),
            'occupation' => $faker->randomElement($array = array ('self-emplyed', 'engineer','doctor', 'writer', 'student', 'tradesman', 'teacher')),
            'height'     => 0,
            'smoking'    => $faker->randomElement($array = array (true, false))  ,  
            'religion'   => $faker->randomElement($array = array ('islam', 'hinduism', 'christian', 'judaism', 'buddhism', 'athiest' )) ,
            'ethnicity'  => $faker->randomElement($array = array ('caucasian', 'hispanic', 'black','middleeast','asian','indian','aboriginal','islander', 'mixed')) ,
            'bio'        => $faker->sentence($nbWords = 6, $variableNbWords = true) ,
            'language1'  => $faker->randomElement($array = array ('english', 'french', 'spanish', 'chinese', 'hindi', 'urdu', null)) ,
            'language2'  => $faker->randomElement($array = array ('english', 'french', 'spanish', 'chinese', 'hindi', 'urdu', null)) ,
            'language3'  => $faker->randomElement($array = array ('english', 'french', 'spanish', 'chinese', 'hindi', 'urdu', null)) ,
            'language4'  => $faker->randomElement($array = array ('english', 'french', 'spanish', 'chinese', 'hindi', 'urdu', null)) ,
            'language5'  => $faker->randomElement($array = array ('english', 'french', 'spanish', 'chinese', 'hindi', 'urdu', null)) ,
            'interest1'  => $faker->randomElement($array = array ('tech', 'science', 'art', 'history', 'sports', 'literature', 'traveling', null)) ,
            'interest2'  => $faker->randomElement($array = array ('tech', 'science', 'art', 'history', 'sports', 'literature', 'traveling', null)) ,
            'interest3'  => $faker->randomElement($array = array ('tech', 'science', 'art', 'history', 'sports', 'literature', 'traveling', null)) ,
            'interest4'  => $faker->randomElement($array = array ('tech', 'science', 'art', 'history', 'sports', 'literature', 'traveling', null)) ,
            'interest5'  => $faker->randomElement($array = array ('tech', 'science', 'art', 'history', 'sports', 'literature', 'traveling', null)) ,
            'hobbies1'   => $faker->randomElement($array = array ('hiking', 'dancing', 'shopping', 'camping', 'gaming', 'writing', 'hunting', 'photography', 'drawing', 'fishing', 'backpacking', 'coin', null)) ,
            'hobbies2'   => $faker->randomElement($array = array ('hiking', 'dancing', 'shopping', 'camping', 'gaming', 'writing', 'hunting', 'photography', 'drawing', 'fishing', 'backpacking', 'coin', null)),
            'hobbies3'   => $faker->randomElement($array = array ('hiking', 'dancing', 'shopping', 'camping', 'gaming', 'writing', 'hunting', 'photography', 'drawing', 'fishing', 'backpacking', 'coin', null)) ,
            'hobbies4'   => $faker->randomElement($array = array ('hiking', 'dancing', 'shopping', 'camping', 'gaming', 'writing', 'hunting', 'photography', 'drawing', 'fishing', 'backpacking', 'coin', null)) ,
            'hobbies5'   => $faker->randomElement($array = array ('hiking', 'dancing', 'shopping', 'camping', 'gaming', 'writing', 'hunting', 'photography', 'drawing', 'fishing', 'backpacking', 'coin', null)) ,
            ]);
        }
    }

    public static $location_table = array(
        'MELBOURNE',
        'EAST MELBOURNE',
        'WEST MELBOURNE',
        'MELBOURNE',
        'WORLD TRADE CENTRE',
        'SOUTHBANK',
        'DOCKLANDS',
        'UNIVERSITY OF MELBOURNE',
        'FOOTSCRAY',
        'SEDDON',
        'SEDDON WEST',
        'BROOKLYN',
        'KINGSVILLE',
        'KINGSVILLE WEST',
        'MAIDSTONE',
        'TOTTENHAM',
        'WEST FOOTSCRAY',
        'YARRAVILLE',
        'YARRAVILLE WEST',
        'NEWPORT',
        'SOUTH KINGSVILLE',
        'SPOTSWOOD',
        'WILLIAMSTOWN',
        'WILLIAMSTOWN NORTH',
        'ALTONA',
        'SEAHOLME',
        'BRAYBROOK',
        'BRAYBROOK NORTH',
        'ROBINSON',
        'ALBION',
        'GLENGALA',
        'SUNSHINE NORTH',
        'SUNSHINE WEST',
        'ALBANVALE',
        'KEALBA',
        'KINGS PARK',
        'ST ALBANS',
        'ARDEER',
        'DEER PARK EAST',
        'BURNSIDE',
        'BURNSIDE HEIGHTS',
        'CAIRNLEA',
        'CAROLINE SPRINGS',
        'DEER PARK',
        'DEER PARK NORTH',
        'RAVENHALL',
        'MAMBOURIN',
        'MOUNT COTTRELL',
        'WYNDHAM VALE',
        'ALTONA EAST',
        'ALTONA GATE',
        'ALTONA NORTH',
        'LAVERTON NORTH',
        'LAVERTON RAAF',
        'ALTONA MEADOWS',
        'LAVERTON',
        'SEABROOK',
        'HOPPERS CROSSING',
        'TARNEIT',
        'TRUGANINA',
        'COCOROC',
        'DERRIMUT',
        'POINT COOK',
        'QUANDONG',
        'WERRIBEE',
        'WERRIBEE SOUTH',
        'FLEMINGTON',
        'KENSINGTON',
        'ASCOT VALE',
        'HIGHPOINT CITY',
        'MARIBYRNONG',
        'TRAVANCORE',
        'KEILOR EAST',
        'AVONDALE HEIGHTS',
        'KEILOR',
        'KEILOR NORTH',
        'DELAHEY',
        'HILLSIDE',
        'SYDENHAM',
        'TAYLORS HILL',
        'KEILOR DOWNS',
        'KEILOR LODGE',
        'TAYLORS LAKES',
        'WATERGARDENS',
        'MOONEE PONDS',
        'ABERFELDIE',
        'ESSENDON',
        'ESSENDON WEST',
        'ESSENDON NORTH',
        'STRATHMORE',
        'STRATHMORE HEIGHTS',
        'AIRPORT WEST',
        'KEILOR PARK',
        'NIDDRIE',
        'GLADSTONE PARK',
        'GOWANBRAE',
        'TULLAMARINE',
        'PASCOE VALE',
        'PASCOE VALE SOUTH',
        'MELBOURNE AIRPORT',
        'GLENROY',
        'HADFIELD',
        'OAK PARK',
        'BROADMEADOWS',
        'DALLAS',
        'JACANA',
        'COOLAROO',
        'MEADOW HEIGHTS',
        'ATTWOOD',
        'CALDER PARK',
        'WESTMEADOWS',
        'ROYAL MELBOURNE HOSPITAL',
        'NORTH MELBOURNE',
        'MELBOURNE UNIVERSITY',
        'PARKVILLE',
        'CARLTON',
        'CARLTON SOUTH',
        'CARLTON NORTH',
        'PRINCES HILL',
        'BRUNSWICK SOUTH',
        'BRUNSWICK WEST',
        'MOONEE VALE',
        'MORELAND WEST',
        'BRUNSWICK',
        'BRUNSWICK LOWER',
        'BRUNSWICK NORTH',
        'BRUNSWICK EAST',
        'BATMAN',
        'COBURG',
        'COBURG NORTH',
        'MERLYNSTON',
        'MORELAND',
        'GREENVALE',
        'FAWKNER',
        'FAWKNER EAST',
        'FAWKNER NORTH',
        'CAMPBELLFIELD',
        'SOMERTON',
        'OAKLANDS JUNCTION',
        'YUROKE',
        'CRAIGIEBURN',
        'DONNYBROOK',
        'KALKALLO',
        'MICKLEHAM',
        'ROXBURGH PARK',
        'FITZROY',
        'COLLINGWOOD',
        'COLLINGWOOD NORTH',
        'ABBOTSFORD',
        'CLIFTON HILL',
        'FITZROY NORTH',
        'NORTHCOTE',
        'NORTHCOTE SOUTH',
        'THORNBURY',
        'NORTHLAND CENTRE',
        'PRESTON',
        'PRESTON LOWER',
        'PRESTON SOUTH',
        'PRESTON WEST',
        'KEON PARK',
        'RESERVOIR',
        'RESERVOIR EAST',
        'RESERVOIR NORTH',
        'RESERVOIR SOUTH',
        'THOMASTOWN',
        'LALOR',
        'LALOR PLAZA',
        'EPPING',
        'ALPHINGTON',
        'FAIRFIELD',
        'IVANHOE',
        'IVANHOE EAST',
        'IVANHOE NORTH',
        'BELLFIELD',
        'HEIDELBERG HEIGHTS',
        'HEIDELBERG WEST',
        'MILL PARK',
        'BUNDOORA',
        'KINGSBURY',
        'LA TROBE UNIVERSITY',
        'BANYULE',
        'EAGLEMONT',
        'HEIDELBERG',
        'ROSANNA',
        'VIEWBANK',
        'MACLEOD',
        'MACLEOD WEST',
        'YALLAMBIE',
        'LA TROBE UNIVERSITY',
        'WATSONIA',
        'WATSONIA NORTH',
        'BRIAR HILL',
        'GREENSBOROUGH',
        'SAINT HELENA',
        'DIAMOND CREEK',
        'PLENTY',
        'YARRAMBAT',
        'LOWER PLENTY',
        'MONTMORENCY',
        'ELTHAM',
        'ELTHAM NORTH',
        'RESEARCH',
        'WATTLE GLEN',
        'BEND OF ISLANDS',
        'KANGAROO GROUND',
        'WATSONS CREEK',
        'ARTHURS CREEK',
        'COTTLES BRIDGE',
        'HURSTBRIDGE',
        'NUTFIELD',
        'STRATHEWEN',
        'COTHAM',
        'KEW',
        'KEW EAST',
        'BALWYN',
        'BALWYN EAST',
        'BALWYN NORTH',
        'GREYTHORN',
        'BULLEEN',
        'TEMPLESTOWE',
        'TEMPLESTOWE LOWER',
        'DONCASTER',
        'DONCASTER EAST',
        'DONCASTER HEIGHTS',
        'THE PINES',
        'DONVALE',
        'NORTH WARRANDYTE',
        'WARRANDYTE',
        'PARK ORCHARDS',
        'WONGA PARK',
        'CHIRNSIDE PARK',
        'BURNLEY',
        'BURNLEY NORTH',
        'CREMORNE',
        'RICHMOND',
        'RICHMOND EAST',
        'RICHMOND NORTH',
        'RICHMOND SOUTH',
        'AUBURN SOUTH',
        'HAWTHORN',
        'HAWTHORN NORTH',
        'HAWTHORN WEST',
        'AUBURN',
        'HAWTHORN EAST',
        'CAMBERWELL',
        'CAMBERWELL NORTH',
        'CAMBERWELL SOUTH',
        'CAMBERWELL WEST',
        'HARTWELL',
        'MIDDLE CAMBERWELL',
        'BENNETTSWOOD',
        'BURWOOD',
        'SURREY HILLS SOUTH',
        'CAMBERWELL EAST',
        'CANTERBURY',
        'MONT ALBERT',
        'SURREY HILLS',
        'SURREY HILLS NORTH',
        'BOX HILL',
        'BOX HILL CENTRAL',
        'BOX HILL SOUTH',
        'HOUSTON',
        'WATTLE PARK',
        'BOX HILL NORTH',
        'KERRIMUIR',
        'MONT ALBERT NORTH',
        'BLACKBURN',
        'BLACKBURN NORTH',
        'BLACKBURN SOUTH',
        'LABURNUM',
        'BRENTFORD SQUARE',
        'FOREST HILL',
        'NUNAWADING',
        'MITCHAM',
        'MITCHAM NORTH',
        'RANGEVIEW',
        'VERMONT',
        'VERMONT SOUTH',
        'RINGWOOD',
        'RINGWOOD NORTH',
        'WARRANDYTE SOUTH',
        'WARRANWOOD',
        'BEDFORD ROAD',
        'HEATHMONT',
        'RINGWOOD EAST',
        'CROYDON',
        'CROYDON HILLS',
        'CROYDON NORTH',
        'CROYDON SOUTH',
        'KILSYTH',
        'KILSYTH SOUTH',
        'MOOROOLBARK',
        'BEENAK',
        'DON VALLEY',
        'HODDLES CREEK',
        'LAUNCHING PLACE',
        'SEVILLE',
        'SEVILLE EAST',
        'WANDIN EAST',
        'WANDIN NORTH',
        'WOORI YALLOCK',
        'YELLINGBO',
        'LILYDALE',
        'CHAPEL STREET NORTH',
        'SOUTH YARRA',
        'HAWKSBURN',
        'TOORAK',
        'ARMADALE',
        'ARMADALE NORTH',
        'KOOYONG',
        'MALVERN',
        'MALVERN NORTH',
        'CAULFIELD EAST',
        'CENTRAL PARK',
        'DARLING',
        'MALVERN EAST',
        'GLEN IRIS',
        'ASHBURTON',
        'ASHWOOD',
        'CHADSTONE',
        'CHADSTONE CENTRE',
        'HOLMESGLEN',
        'MOUNT WAVERLEY',
        'PINEWOOD',
        'SYNDAL',
        'GLEN WAVERLEY',
        'WHEELERS HILL',
        'BURWOOD EAST',
        'BURWOOD HEIGHTS',
        'KNOX CITY CENTRE',
        'WANTIRNA',
        'WANTIRNA SOUTH',
        'BAYSWATER',
        'BAYSWATER NORTH',
        'THE BASIN',
        'BORONIA',
        'FERNTREE GULLY',
        'LYSTERFIELD',
        'LYSTERFIELD SOUTH',
        'MOUNTAIN GATE',
        'UPPER FERNTREE GULLY',
        'UPWEY',
        'MENZIES CREEK',
        'SELBY',
        'BELGRAVE',
        'BELGRAVE HEIGHTS',
        'BELGRAVE SOUTH',
        'TECOMA',
        'CAULFIELD JUNCTION',
        'CAULFIELD NORTH',
        'CAULFIELD',
        'CAULFIELD SOUTH',
        'HOPETOUN GARDENS',
        'CARNEGIE',
        'GLEN HUNTLY',
        'MURRUMBEENA',
        'DANDENONG SOUTH',
        'BENTLEIGH EAST',
        'COATESVILLE',
        'HUGHESDALE',
        'HUNTINGDALE',
        'OAKLEIGH',
        'OAKLEIGH EAST',
        'OAKLEIGH SOUTH',
        'CLAYTON',
        'NOTTING HILL',
        'CLARINDA',
        'CLAYTON SOUTH',
        'MULGRAVE',
        'WAVERLEY GARDENS',
        'SANDOWN VILLAGE',
        'SPRINGVALE',
        'DINGLEY VILLAGE',
        'SPRINGVALE SOUTH',
        'KEYSBOROUGH',
        'NOBLE PARK',
        'NOBLE PARK EAST',
        'NOBLE PARK NORTH',
        'BANGHOLME',
        'DANDENONG',
        'DANDENONG EAST',
        'DANDENONG NORTH',
        'DANDENONG SOUTH',
        'DUNEARN',
        'DOVETON',
        'EUMEMMERRING',
        'ROWVILLE',
        'SCORESBY',
        'KNOXFIELD',
        'PRAHRAN',
        'PRAHRAN EAST',
        'WINDSOR',
        'ST KILDA',
        'ST KILDA WEST',
        'BALACLAVA',
        'ST KILDA EAST',
        'BRIGHTON ROAD',
        'ELWOOD',
        'ELSTERNWICK',
        'GARDENVALE',
        'RIPPONLEA',
        'BRIGHTON',
        'BRIGHTON NORTH',
        'DENDY',
        'BRIGHTON EAST',
        'NORTH ROAD',
        'HAMPTON EAST',
        'HAMPTON NORTH',
        'MOORABBIN',
        'WISHART',
        'HIGHETT',
        'SANDRINGHAM',
        'CHELTENHAM',
        'CHELTENHAM EAST',
        'CHELTENHAM NORTH',
        'SOUTHLAND CENTRE',
        'BEAUMARIS',
        'BLACK ROCK',
        'BLACK ROCK NORTH',
        'CROMER',
        'MENTONE',
        'MENTONE EAST',
        'MOORABBIN AIRPORT',
        'ASPENDALE',
        'ASPENDALE GARDENS',
        'BRAESIDE',
        'MORDIALLOC',
        'PARKDALE',
        'WATERWAYS',
        'BONBEACH',
        'CHELSEA',
        'CHELSEA HEIGHTS',
        'EDITHVALE',
        'CARRUM',
        'PATTERSON LAKES',
        'BELVEDERE PARK',
        'SEAFORD',
        'FRANKSTON',
        'FRANKSTON EAST',
        'FRANKSTON HEIGHTS',
        'FRANKSTON SOUTH',
        'KARINGAL',
        'KARINGAL CENTRE',
        'FRANKSTON NORTH',
        'PINES FOREST',
        'CARRUM DOWNS',
        'HEATHERTON',
        'BENTLEIGH',
        'MCKINNON',
        'ORMOND',
        'PATTERSON',
        'SOUTH MELBOURNE',
        'ALBERT PARK',
        'MIDDLE PARK',
        'GARDEN CITY',
        'PORT MELBOURNE',
        'LITTLE RIVER',
        'LARA',
        'POINT WILSON',
        'CORIO',
        'NORLANE',
        'NORTH SHORE',
        'BELL PARK',
        'BELL POST HILL',
        'DRUMCONDRA',
        'GEELONG NORTH',
        'HAMLYN HEIGHTS',
        'NORTH GEELONG',
        'RIPPLESIDE',
        'BELMONT',
        'FRESHWATER CREEK',
        'GROVEDALE',
        'GROVEDALE EAST',
        'HIGHTON',
        'MOUNT DUNEED',
        'WANDANA HEIGHTS',
        'WAURN PONDS',
        'DEAKIN UNIVERSITY',
        'GEELONG WEST',
        'HERNE HILL',
        'MANIFOLD HEIGHTS',
        'BREAKWATER',
        'EAST GEELONG',
        'NEWCOMB',
        'ST ALBANS PARK',
        'THOMSON',
        'WHITTINGTON',
        'BAREENA',
        'GEELONG',
        'NEWTOWN',
        'SOUTH GEELONG',
        'ANAKIE',
        'BARRABOOL',
        'BATESFORD',
        'BELLARINE',
        'CERES',
        'FYANSFORD',
        'GNARWARRE',
        'GREY RIVER',
        'KENNETT RIVER',
        'LOVELY BANKS',
        'MOOLAP',
        'MOORABOOL',
        'MURGHEBOLUC',
        'SEPARATION CREEK',
        'STAUGHTON VALE',
        'STONEHAVEN',
        'SUGARLOAF',
        'WALLINGTON',
        'WONGARRA',
        'WYE RIVER',
        'CLIFTON SPRINGS',
        'CURLEWIS',
        'DRYSDALE',
        'MANNERIM',
        'MARCUS HILL',
        'INDENTED HEAD',
        'PORTARLINGTON',
        'ST LEONARDS',
        'LEOPOLD',
        'POINT LONSDALE',
        'QUEENSCLIFF',
        'SWAN BAY',
        'SWAN ISLAND',
        'OCEAN GROVE',
        'BARWON HEADS',
        'BREAMLEA',
        'CONNEWARRE',
        'BELLBRAE',
        'BELLS BEACH',
        'JAN JUC',
        'TORQUAY',
        'ANGLESEA',
        'AIREYS INLET',
        'BIG HILL',
        'EASTERN VIEW',
        'FAIRHAVEN',
        'MOGGS CREEK',
        'LORNE',
        'APOLLO BAY',
        'CAPE OTWAY',
        'MARENGO',
        'PETTICOAT CREEK',
        'SKENES CREEK',
        'SKENES CREEK NORTH',
        'BENWERRIN',
        'BOONAH',
        'DEANS MARSH',
        'PENNYROYAL',
        'FORREST',
        'MOUNT SABINE',
        'AIRE VALLEY',
        'BEECH FOREST',
        'GELLIBRAND LOWER',
        'WATTLE HILL',
        'WEEAPROINAH',
        'WYELANGTA',
        'YUULONG',
        'GLENAIRE',
        'HORDERN VALE',
        'JOHANNA',
        'LAVERS HILL',
        'CARLISLE RIVER',
        'CHAPPLE VALE',
        'GELLIBRAND',
        'KENNEDYS CREEK',
        'BUCKLEY',
        'GHERANG',
        'MODEWARRE',
        'MORIAC',
        'MOUNT MORIAC',
        'PARAPARAP',
        'BAMBRA',
        'OMBERSLEY',
        'WENSLEYDALE',
        'WINCHELSEA',
        'WINCHELSEA SOUTH',
        'WURDIBOLUC',
        'BIRREGURRA',
        'BARWON DOWNS',
        'GERANGAMETE',
        'MURROON',
        'WARNCOORT',
        'WHOOREL',
        'ALVIE',
        'BALINTORE',
        'BARONGAROOK',
        'BARONGAROOK WEST',
        'BARRAMUNGA',
        'CORAGULAC',
        'CORUNNUN',
        'DREEITE',
        'DREEITE SOUTH',
        'IRREWARRA',
        'IRREWILLIPE',
        'IRREWILLIPE EAST',
        'KAWARREN',
        'LARPENT',
        'NALANGIL',
        'ONDIT',
        'PIRRON YALLOCK',
        'POMBORNEIT EAST',
        'SWAN MARSH',
        'TANYBRYN',
        'WARRION',
        'WOOL WOOL',
        'YEO',
        'YEODENE',
        'COLAC',
        'COLAC EAST',
        'COLAC WEST',
        'ELLIMINYT',
        'BEEAC',
        'CUNDARE NORTH',
        'EURACK',
        'WEERING',
        'COROROOKE',
        'BOOKAAR',
        'BOSTOCKS CREEK',
        'BUNGADOR',
        'CAMPERDOWN',
        'CARPENDEIT',
        'CHOCOLYN',
        'GNOTUK',
        'KARIAH',
        'KOALLAH',
        'LESLIE MANOR',
        'POMBORNEIT',
        'POMBORNEIT NORTH',
        'SKIBO',
        'SOUTH PURRUMBETE',
        'STONYFORD',
        'TANDAROOK',
        'TESBURY',
        'WEERITE',
        'TERANG',
        'BOORCAN',
        'CUDGEE',
        'DIXIE',
        'ECKLIN SOUTH',
        'ELLERSLIE',
        'FRAMLINGHAM',
        'FRAMLINGHAM EAST',
        'GARVOC',
        'GLENORMISTON NORTH',
        'GLENORMISTON SOUTH',
        'KOLORA',
        'LAANG',
        'NOORAT',
        'NOORAT EAST',
        'PANMURE',
        'TAROON',
        'THE SISTERS',
        'BULLAHARRE',
        'COBDEN',
        'COBRICO',
        'ELINGAMITE',
        'ELINGAMITE NORTH',
        'GLENFYNE',
        'JANCOURT',
        'JANCOURT EAST',
        'NAROGHID',
        'SIMPSON',
        'SCOTTS CREEK',
        'AYRFORD',
        'BRUCKNELL',
        'COORIEMUNGLE',
        'COWLEYS CREEK',
        'CURDIES RIVER',
        'CURDIEVALE',
        'HEYTESBURY LOWER',
        'NEWFIELD',
        'NIRRANDA',
        'NIRRANDA EAST',
        'NIRRANDA SOUTH',
        'NULLAWARRE',
        'PAARATTE',
        'THE COVE',
        'TIMBOON',
        'TIMBOON WEST',
        'PORT CAMPBELL',
        'PRINCETOWN',
        'WAARRE',
        'PETERBOROUGH',
        'DARLINGTON',
        'DUNDONNELL',
        'PURA PURA',
        'MORTLAKE',
        'WOORNDOO',
        'HEXHAM',
        'CARAMUT',
        'MAILORS FLAT',
        'MINJAH',
        'WOOLSTHORPE',
        'ALLANSFORD',
        'MEPUNGA',
        'MEPUNGA EAST',
        'MEPUNGA WEST',
        'NARINGAL',
        'NARINGAL EAST',
        'PURNIM',
        'PURNIM WEST',
        'BALLANGEICH',
        'WANGOOM',
        'DENNINGTON',
        'WARRNAMBOOL',
        'WARRNAMBOOL EAST',
        'WARRNAMBOOL WEST',
        'BUSHFIELD',
        'GRASSMERE',
        'WINSLOW',
        'WOODFORD',
        'ILLOWA',
        'KOROIT',
        'CROSSLEY',
        'KILLARNEY',
        'KIRKSTALL',
        'SOUTHERN CROSS',
        'TARRONE',
        'TOWER HILL',
        'WARRONG',
        'WILLATOOK',
        'YANGERY',
        'YARPTURK',
        'ORFORD',
        'PORT FAIRY',
        'CODRINGTON',
        'NARRAWONG',
        'ROSEBROOK',
        'ST HELENS',
        'TOOLONG',
        'TYRENDARRA',
        'TYRENDARRA EAST',
        'YAMBUK',
        'CONDAH SWAMP',
        'KNEBSWORTH',
        'MACARTHUR',
        'RIPPONHURST',
        'WARRABKOOK',
        'HAWKESDALE',
        'MINHAMITE',
        'GAZETTE',
        'GERRIGERRUP',
        'PENSHURST',
        'PURDEET',
        'TABOR',
        'NELSON',
        'GLENTHOMPSON',
        'NAREEB',
        'NARRAPUMELAP SOUTH',
        'DUNKELD',
        'KARABEAL',
        'MIRRANATWA',
        'MOUTAJUP',
        'VICTORIA POINT',
        'VICTORIA VALLEY',
        'WOODHOUSE',
        'BYADUK NORTH',
        'HAMILTON',
        'BOCHARA',
        'BROADWATER',
        'BUCKLEY SWAMP',
        'BYADUK',
        'CROXTON EAST',
        'HENSLEY PARK',
        'MORGIANA',
        'MOUNT NAPIER',
        'STRATHKELLAR',
        'TAHARA',
        'TARRINGTON',
        'WANNON',
        'WARRAYURE',
        'YATCHAW',
        'YULECART',
        'BRANXHOLME',
        'GRASSDALE',
        'BREAKAWAY CREEK',
        'CONDAH',
        'HOTSPUR',
        'LAKE CONDAH',
        'WALLACEDALE',
        'BESSIEBELLE',
        'DARTMOOR',
        'DRIK DRIK',
        'DRUMBORG',
        'GREENWALD',
        'HEYWOOD',
        'HOMERTON',
        'LYONS',
        'MILLTOWN',
        'MUMBANNAR',
        'MYAMYN',
        'WINNAP',
        'ALLESTREE',
        'BOLWARRA',
        'CAPE BRIDGEWATER',
        'CASHMORE',
        'DUTTON WAY',
        'GORAE',
        'GORAE WEST',
        'HEATHMERE',
        'MOUNT RICHMOND',
        'PORTLAND',
        'PORTLAND NORTH',
        'PORTLAND WEST',
        'DIGBY',
        'MERINO',
        'TAHARA WEST',
        'CASTERTON',
        'CORNDALE',
        'BAHGALLAH',
        'BRIMBOAL',
        'CARAPOOK',
        'CHETWYND',
        'DERGHOLM',
        'DORODONG',
        'DUNROBIN',
        'HENTY',
        'KILLARA',
        'LAKE MUNDI',
        'LINDSAY',
        'NANGEELA',
        'POOLAIJELO',
        'POWERS CREEK',
        'SANDFORD',
        'STRATHDOWNIE',
        'WANDO BRIDGE',
        'WANDO VALE',
        'WARROCK',
        'BULART',
        'CAVENDISH',
        'GLENISLA',
        'GRAMPIANS',
        'MOORALLA',
        'WOOHLPOOER',
        'BRIT BRIT',
        'CLOVER FLAT',
        'COLERAINE',
        'COOJAR',
        'CULLA',
        'GRINGEGALGONA',
        'GRITJURK',
        'HILGAY',
        'KONONGWOOTONG',
        'MELVILLE FOREST',
        'MUNTHAM',
        'NAREEN',
        'PASCHENDALE',
        'TAHARA BRIDGE',
        'TARRAYOUKYAN',
        'TARRENLEA',
        'WOOTONG VALE',
        'HARROW',
        'CHARAM',
        'CONNEWIRRICOO',
        'EDENHOPE',
        'KADNOOK',
        'LANGKOOP',
        'PATYAH',
        'ULLSWATER',
        'APSLEY',
        'BENAYEO',
        'BRINGALBERT',
        'HESSE',
        'INVERLEIGH',
        'WINGEEL',
        'CRESSY',
        'BERRYBANK',
        'DUVERNEY',
        'FOXHOW',
        'LISMORE',
        'MINGAY',
        'MOUNT BUTE',
        'DERRINALLUM',
        'LARRALEA',
        'VITE VITE',
        'VITE VITE NORTH',
        'TEESDALE',
        'BARUNAH PARK',
        'SHELFORD',
        'ROKEWOOD',
        'BANNOCKBURN',
        'GHERINGHAP',
        'MAUDE',
        'RUSSELLS BRIDGE',
        'SHE OAKS',
        'STEIGLITZ',
        'SUTHERLANDS CREEK',
        'LETHBRIDGE',
        'BAMGANIE',
        'MEREDITH',
        'BUNGAL',
        'CARGERIE',
        'ELAINE',
        'MOUNT DORAN',
        'PLUMPTON',
        'ROCKBANK',
        'KURUNJANG',
        'MELTON',
        'MELTON WEST',
        'TOOLERN VALE',
        'BROOKFIELD',
        'EXFORD',
        'EYNESBURY',
        'MELTON SOUTH',
        'BACCHUS MARSH',
        'BALLIANG',
        'BALLIANG EAST',
        'COIMADAI',
        'DARLEY',
        'GLENMORE',
        'HOPETOUN PARK',
        'LONG FOREST',
        'MADDINGLEY',
        'MERRIMU',
        'PARWAN',
        'ROWSLEY',
        'DALES CREEK',
        'GREENDALE',
        'KOROBEIT',
        'MYRNIONG',
        'PENTLAND HILLS',
        'BALLAN',
        'BEREMBOKE',
        'BLAKEVILLE',
        'BUNDING',
        'COLBROOK',
        'DURDIDWARRAH',
        'FISKVILLE',
        'INGLISTON',
        'MOUNT WALLACE',
        'GORDON',
        'ALFREDTON',
        'BAKERY HILL',
        'BALLARAT',
        'BALLARAT CENTRAL',
        'BALLARAT EAST',
        'BALLARAT NORTH',
        'BALLARAT WEST',
        'BLACK HILL',
        'BROWN HILL',
        'CANADIAN',
        'EUREKA',
        'GOLDEN POINT',
        'INVERMAY PARK',
        'LAKE WENDOUREE',
        'MOUNT CLEAR',
        'MOUNT HELEN',
        'MOUNT PLEASANT',
        'NERRINA',
        'NEWINGTON',
        'REDAN',
        'SOLDIERS HILL',
        'SOVEREIGN HILL',
        'BERRINGA',
        'BO PEEP',
        'CAPE CLEAR',
        'CARNGHAM',
        'CHEPSTOWE',
        'HADDON',
        'HAPPY VALLEY',
        'HILLCREST',
        'ILLABAROOK',
        'LAKE BOLAC',
        'MININERA',
        'MOUNT EMU',
        'NERRIN NERRIN',
        'NEWTOWN',
        'NINTINGBOOL',
        'PIGGOREET',
        'PITFIELD',
        'ROKEWOOD JUNCTION',
        'ROSS CREEK',
        'SCARSDALE',
        'SMYTHES CREEK',
        'SMYTHESDALE',
        'SNAKE VALLEY',
        'SPRINGDALLAH',
        'STAFFORDSHIRE REEF',
        'STREATHAM',
        'WALLINDUC',
        'WESTMERE',
        'ADDINGTON',
        'BARKSTEAD',
        'BLOWHARD',
        'BOLWARRAH',
        'BREWSTER',
        'BULLAROOK',
        'BUNGAREE',
        'BUNKERS HILL',
        'BURRUMBEET',
        'CAMBRIAN HILL',
        'CARDIGAN',
        'CARDIGAN VILLAGE',
        'CHAPEL FLAT',
        'CLARENDON',
        'CLARETOWN',
        'CLARKES HILL',
        'CORINDHAP',
        'DEREEL',
        'DUNNSTOWN',
        'DURHAM LEAD',
        'ENFIELD',
        'ERCILDOUNE',
        'GARIBALDI',
        'GLEN PARK',
        'GLENBRAE',
        'GONG GONG',
        'GRENVILLE',
        'INVERMAY',
        'LAL LAL',
        'LAMPLOUGH',
        'LANGI KAL KAL',
        'LEARMONTH',
        'LEIGH CREEK',
        'LEXTON',
        'MAGPIE',
        'MILLBROOK',
        'MINERS REST',
        'MITCHELL PARK',
        'MOLLONGGHIP',
        'MOUNT BOLTON',
        'MOUNT EGERTON',
        'MOUNT MERCER',
        'MOUNT MITCHELL',
        'MOUNT ROWAN',
        'NAPOLEONS',
        'NAVIGATORS',
        'POOTILLA',
        'SCOTSBURN',
        'SPRINGBANK',
        'SULKY',
        'WALLACE',
        'WARRENHEIP',
        'WATTLE FLAT',
        'WAUBRA',
        'WEATHERBOARD',
        'WERNETH',
        'YENDON',
        'BALLARAT',
        'BAKERY HILL',
        'LAKE GARDENS',
        'MITCHELL PARK',
        'WENDOUREE',
        'WENDOUREE VILLAGE',
        'BONSHAW',
        'DELACOMBE',
        'SEBASTOPOL',
        'BUNINYONG',
        'LINTON',
        'MANNIBADAR',
        'PITTONG',
        'WILLOWVALE',
        'BRADVALE',
        'CARRANBALLAC',
        'SKIPTON',
        'CRESWICK',
        'CRESWICK NORTH',
        'DEAN',
        'GLENDARUEL',
        'LANGDONS HILL',
        'MOUNT BECKWORTH',
        'TOURELLO',
        'ALLENDALE',
        'ASCOT',
        'BALD HILLS',
        'BLAMPIED',
        'BROOMFIELD',
        'CABBAGE TREE',
        'CAMPBELLTOWN',
        'COGHILLS CREEK',
        'GLENDONNELL',
        'KINGSTON',
        'KOOROOCHEANG',
        'LAWRENCE',
        'MOUNT PROSPECT',
        'NEWLYN',
        'NEWLYN NORTH',
        'ROCKLYN',
        'SMEATON',
        'SMOKEYTOWN',
        'SPRINGMOUNT',
        'STRATHLEA',
        'WERONA',
        'CLUNES',
        'GLENGOWER',
        'MOUNT CAMERON',
        'ULLINA',
        'AMHERST',
        'BURNBANK',
        'CARALULUP',
        'DUNACH',
        'EVANSFORD',
        'LILLICUR',
        'MOUNT GLASGOW',
        'STONY CREEK',
        'TALBOT',
        'BEAUFORT',
        'CHUTE',
        'CROSS ROADS',
        'LAKE GOLDSMITH',
        'LAKE WONGAN',
        'MAIN LEAD',
        'MENA PARK',
        'NERRING',
        'RAGLAN',
        'SHIRLEY',
        'STOCKYARD HILL',
        'STONELEIGH',
        'TRAWALLA',
        'WATERLOO',
        'BALLYROGAN',
        'BAYINDEEN',
        'BUANGOR',
        'MIDDLE CREEK',
        'ARARAT',
        'ARMSTRONG',
        'CATHCART',
        'CROWLANDS',
        'DENICULL CREEK',
        'DOBIE',
        'DUNNEWORTHY',
        'EVERSLEY',
        'GREAT WESTERN',
        'LANGI LOGAN',
        'MAROONA',
        'MOUNT COLE',
        'MOUNT COLE CREEK',
        'MOYSTON',
        'NORVAL',
        'RHYMNEY',
        'ROCKY POINT',
        'ROSSBRIDGE',
        'WARRAK',
        'TATYOON',
        'YALLA-Y-POORA',
        'BORNES HILL',
        'CHATSWORTH',
        'MAFEKING',
        'STAVELY',
        'WICKLIFFE',
        'WILLAURA',
        'WILLAURA NORTH',
        'BELLELLEN',
        'BRIDGE INN',
        'MOKEPILLY',
        'STAWELL',
        'STAWELL WEST',
        'WINJALLOK',
        'BARKLY',
        'BELLFIELD',
        'BOLANGUM',
        'CALLAWADDA',
        'CAMPBELLS BRIDGE',
        'CONCONGELLA',
        'DEEP LEAD',
        'FYANS CREEK',
        'GERMANIA',
        'GREENS CREEK',
        'HALLS GAP',
        'ILLAWARRA',
        'JOEL JOEL',
        'JOEL SOUTH',
        'KANYA',
        'LAKE FYANS',
        'LAKE LONSDALE',
        'LUBECK',
        'MORRL MORRL',
        'PARADISE',
        'POMONAL',
        'ROSTRON',
        'WAL WAL',
        'WALLALOO',
        'WALLALOO EAST',
        'FRENCHMANS',
        'LANDSBOROUGH',
        'LANDSBOROUGH WEST',
        'NAVARRE',
        'SHAYS FLAT',
        'WATTLE CREEK',
        'DADSWELLS BRIDGE',
        'GLENORCHY',
        'LEDCOURT',
        'RIACHELLA',
        'MARNOO',
        'BANYENA',
        'RUPANYUP',
        'KEWELL',
        'MURTOA',
        'BRIM',
        'MINYIP',
        'SHEEP HILLS',
        'AILSA',
        'ANGIP',
        'AUBREY',
        'BANGERANG',
        'CANNUM',
        'CRYMELON',
        'KELLALAC',
        'LAH',
        'WARRACKNABEAL',
        'WILKUR',
        'WILLENABRINA',
        'BEULAH',
        'KENMARE',
        'HOPETOUN',
        'HOPEVALE',
        'YARTO',
        'HORSHAM',
        'HORSHAM WEST',
        'BLACKHEATH',
        'BRIMPAEN',
        'BUNGALALLY',
        'CHERRYPOOL',
        'DOOEN',
        'DRUNG',
        'GYMBOWEN',
        'HAVEN',
        'HORSHAM',
        'JUNG',
        'KALKEE',
        'KANAGULK',
        'KARNAK',
        'LAHARUM',
        'LONGERENONG',
        'LOWER NORTON',
        'MCKENZIE CREEK',
        'MOCKINYA',
        'MURRA WARRA',
        'NURCOUNG',
        'NURRABIEL',
        'PIMPINIO',
        'QUANTONG',
        'RIVERSIDE',
        'ROCKLANDS',
        'ST HELENS PLAINS',
        'TELANGATUK EAST',
        'TOOLONDO',
        'VECTIS',
        'WAIL',
        'WALLUP',
        'WARTOOK',
        'WONWONDAH',
        'ZUMSTEINS',
        'HORSHAM',
        'BALMORAL',
        'ENGLEFIELD',
        'GATUM',
        'PIGEON PONDS',
        'VASEY',
        'ARAPILES',
        'CLEAR LAKE',
        'DOUGLAS',
        'DUCHEMBEGARRA',
        'GRASS FLAT',
        'JILPANGER',
        'MIGA LAKE',
        'MITRE',
        'NATIMUK',
        'NORADJUHA',
        'TOOAN',
        'WOMBELANO',
        'GOROKE',
        'MINIMAY',
        'NEUARPURR',
        'OZENKADNOOK',
        'PERONNE',
        'ANTWERP',
        'DIMBOOLA',
        'TARRANYURK',
        'MIRAM',
        'BROUGHTON',
        'GERANG GERUNG',
        'GLENLEE',
        'KIATA',
        'LAWLOIT',
        'LITTLE DESERT',
        'LORQUON',
        'NETHERBY',
        'NHILL',
        'YANAC',
        'KANIVA',
        'LILLIMUR',
        'SERVICETON',
        'TELOPEA DOWNS',
        'JEPARIT',
        'ALBACUTYA',
        'YAAPEET',
        'DIGGERS REST',
        'BULLA',
        'SUNBURY',
        'WILDWOOD',
        'CLARKEFIELD',
        'RIDDELLS CREEK',
        'BOLINDA',
        'CHEROKEE',
        'KERRIE',
        'ROMSEY',
        'SPRINGFIELD',
        'BENLOCH',
        'GOLDIE',
        'LANCEFIELD',
        'NULLA VALE',
        'BULLENGAROOK',
        'GISBORNE',
        'GISBORNE SOUTH',
        'NEW GISBORNE',
        'MACEDON',
        'MOUNT MACEDON',
        'ASHBOURNE',
        'CADELLO',
        'CARLSRUHE',
        'COBAW',
        'HANGING ROCK',
        'HESKET',
        'NEWHAM',
        'ROCHFORD',
        'WOODEND',
        'WOODEND NORTH',
        'BARFOLD',
        'BAYNTON',
        'BAYNTON EAST',
        'EDGECOMBE',
        'GLENHOPE',
        'GREENHILL',
        'KYNETON',
        'KYNETON SOUTH',
        'LANGLEY',
        'LAURISTON',
        'LYAL',
        'METCALFE EAST',
        'MIA MIA',
        'MYRTLE CREEK',
        'PASTORIA',
        'PASTORIA EAST',
        'PIPERS CREEK',
        'REDESDALE',
        'SIDONIA',
        'SPRING HILL',
        'TYLDEN',
        'TYLDEN SOUTH',
        'DRUMMOND NORTH',
        'MALMSBURY',
        'TARADALE',
        'ELPHINSTONE',
        'METCALFE',
        'SUTTON GRANGE',
        'CASTLEMAINE',
        'MOONLIGHT FLAT',
        'BARKERS CREEK',
        'CAMPBELLS CREEK',
        'CHEWTON',
        'CHEWTON BUSHLANDS',
        'FARADAY',
        'FRYERSTOWN',
        'GLENLUCE',
        'GOLDEN POINT',
        'GOWER',
        'GUILDFORD',
        'IRISHTOWN',
        'MCKENZIE HILL',
        'MUCKLEFORD',
        'TARILTA',
        'VAUGHAN',
        'YAPEEN',
        'HARCOURT',
        'HARCOURT NORTH',
        'RAVENSWOOD',
        'RAVENSWOOD SOUTH',
        'BARRYS REEF',
        'BLACKWOOD',
        'FERN HILL',
        'LERDERDERG',
        'LITTLE HAMPTON',
        'NEWBURY',
        'NORTH BLACKWOOD',
        'TRENTHAM',
        'TRENTHAM EAST',
        'BASALT',
        'DAYLESFORD',
        'BULLARTO',
        'BULLARTO SOUTH',
        'CLYDESDALE',
        'COOMOORA',
        'DENVER',
        'DRUMMOND',
        'DRY DIGGINGS',
        'EGANSTOWN',
        'ELEVATED PLAINS',
        'FRANKLINFORD',
        'GLENLYON',
        'HEPBURN',
        'HEPBURN SPRINGS',
        'KORWEINGUBOORA',
        'LEONARDS HILL',
        'LYONVILLE',
        'MOUNT FRANKLIN',
        'MUSK',
        'MUSK VALE',
        'PORCUPINE RIDGE',
        'SAILORS FALLS',
        'SAILORS HILL',
        'SHEPHERDS FLAT',
        'SPARGO CREEK',
        'STRANGWAYS',
        'WHEATSHEAF',
        'YANDOIT',
        'YANDOIT HILLS',
        'GREEN GULLY',
        'JOYCES CREEK',
        'MUCKLEFORD SOUTH',
        'NEWSTEAD',
        'SANDON',
        'WELSHMANS REEF',
        'BARINGHUP',
        'BARINGHUP WEST',
        'BRADFORD',
        'EASTVILLE',
        'LAANECOORIE',
        'MALDON',
        'NEEREMAN',
        'NUGGETTY',
        'PERKINS REEF',
        'PORCUPINE FLAT',
        'SHELBOURNE',
        'TARRENGOWER',
        'WALMER',
        'WOODSTOCK WEST',
        'CARISBROOK',
        'ADELAIDE LEAD',
        'ALMA',
        'BOWENVALE',
        'BUNG BONG',
        'COTSWOLD',
        'CRAIGIE',
        'DAISY HILL',
        'FLAGSTAFF',
        'GOLDEN POINT',
        'HAVELOCK',
        'HOMEBUSH',
        'MAJORCA',
        'MARYBOROUGH',
        'MOOLORT',
        'MOONLIGHT FLAT',
        'NATTE YALLOCK',
        'RATHSCAR',
        'RATHSCAR WEST',
        'RODBOROUGH',
        'SIMSON',
        'TIMOR',
        'TIMOR WEST',
        'WAREEK',
        'AVOCA',
        'MOYREISK',
        'AMPHITHEATRE',
        'MOUNT LONARCH',
        'ELMHURST',
        'GLENLOFTY',
        'GLENLOGIE',
        'GLENPATRICK',
        'NOWHERE CREEK',
        'BET BET',
        'BETLEY',
        'BROMLEY',
        'DUNLUCE',
        'DUNOLLY',
        'EDDINGTON',
        'GOLDSBOROUGH',
        'INKERMAN',
        'MCINTYRE',
        'MOLIAGUL',
        'MOUNT HOOGHLY',
        'ARCHDALE',
        'ARCHDALE JUNCTION',
        'BEALIBA',
        'BURKES FLAT',
        'COCHRANES CREEK',
        'EMU',
        'LOGAN',
        'AVON PLAINS',
        'BEAZLEYS BRIDGE',
        'CARAPOOEE',
        'CARAPOOEE WEST',
        'COONOOER BRIDGE',
        'COONOOER WEST',
        'DOOBOOBETIC',
        'GOOROC',
        'GOWAR EAST',
        'GRE GRE',
        'GRE GRE NORTH',
        'GRE GRE SOUTH',
        'KOOREH',
        'MEDLYN',
        'MOOLERR',
        'MOONAMBEL',
        'PERCYDALE',
        'REDBANK',
        'SLATY CREEK',
        'ST ARNAUD',
        'ST ARNAUD EAST',
        'ST ARNAUD NORTH',
        'STUART MILL',
        'SUTHERLAND',
        'SWANWATER',
        'TANWOOD',
        'TOTTINGTON',
        'TRAYNORS LAGOON',
        'TULKARA',
        'WARRENMANG',
        'YAWONG HILLS',
        'AREEGRA',
        'BANYENONG',
        'BOOLITE',
        'CARRON',
        'COPE COPE',
        'CORACK',
        'CORACK EAST',
        'DONALD',
        'GIL GIL',
        'JEFFCOTT',
        'JEFFCOTT NORTH',
        'LAEN',
        'LAEN EAST',
        'LAEN NORTH',
        'LAKE BULOKE',
        'LAWLER',
        'LITCHFIELD',
        'RICH AVON',
        'RICH AVON EAST',
        'RICH AVON WEST',
        'SWANWATER WEST',
        'MASSEY',
        'MORTON PLAINS',
        'WARMUR',
        'WATCHEM',
        'WATCHEM WEST',
        'BALLAPUR',
        'BIRCHIP',
        'BIRCHIP WEST',
        'CURYO',
        'JIL JIL',
        'KARYRIE',
        'KINNABULLA',
        'MARLBED',
        'NARRAPORT',
        'REEDY DAM',
        'WHIRILY',
        'BANYAN',
        'WATCHUPGA',
        'WILLANGIE',
        'WOOMELANG',
        'LASCELLES',
        'SPEED',
        'TURRIFF EAST',
        'TEMPY',
        'BOINKA',
        'KULWIN'
       );

    }
